# Generated by Django 4.1.3 on 2022-12-03 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_match_team_a_goal_alter_match_team_b_goal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Jogo', 'verbose_name_plural': 'Jogos'},
        ),
        migrations.AlterModelOptions(
            name='myteam',
            options={'verbose_name': 'Meu time', 'verbose_name_plural': 'Meus times'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Jogador', 'verbose_name_plural': 'Jogadores'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Time', 'verbose_name_plural': 'Times'},
        ),
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateTimeField(verbose_name='Data do jogo'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_a_matches', to='app.team', verbose_name='Time A'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_a_goal',
            field=models.IntegerField(default=0, verbose_name='Gols do time A'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_b_matches', to='app.team', verbose_name='Time B'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b_goal',
            field=models.IntegerField(default=0, verbose_name='Gols do time B'),
        ),
        migrations.AlterField(
            model_name='myteam',
            name='players',
            field=models.ManyToManyField(to='app.player', verbose_name='Jogadores'),
        ),
        migrations.AlterField(
            model_name='player',
            name='initial_price',
            field=models.FloatField(verbose_name='Preço inicial'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.IntegerField(verbose_name='Minutos')),
                ('action', models.CharField(choices=[('goal', 'Gol'), ('assist', 'Assistência'), ('yellow card', 'Cartão amarelo'), ('red card', 'Cartão vermelho')], max_length=50, verbose_name='Ação')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.match', verbose_name='Jogo')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.player', verbose_name='Jogador')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.team', verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Ação do jogo',
                'verbose_name_plural': 'Ações do jogo',
            },
        ),
    ]
